1. Create a 3x3 array that contains a diagonal of nines.

In [23]:
import numpy as np
arr = np.diag([9,9,9])
print(arr)

[[9 0 0]
 [0 9 0]
 [0 0 9]]


2. Create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive) and use boolean indexing to pick out the values that are within 1/2 standard deviations of the mean.


In [30]:
even_arr = np.arange(2,33,2)
org_mean = np.mean(even_arr)
half_std = np.std(even_arr) / 2
custem_arr = even_arr[ (even_arr < org_mean + half_std) & (even_arr > org_mean - half_std)]
print(custem_arr)

[14 16 18 20]


3. Create a 9x9 array that contains only zeros of type int.

In [33]:
zeros_arr = np.zeros((9,9),dtype=int)
print(zeros_arr)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


4. Ask the user for a number n. Then, use broadcasting to create a n x n ndarray that has its first column full of ones, its second column full of twos, its third column full of threes, etc...

In [41]:
num = int(input("Enter Number : ").strip())
new_arr = np.full((num,num),1) * np.arange(1,num+1)
print(new_arr)

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
